AllCops:
  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

MultilineOperationIndentation:
  EnforcedStyle: indented

MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 25
