AllCops:
  TargetRubyVersion: 2.5

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

MultilineMethodCallIndentation:
  EnforcedStyle: indented

MultilineOperationIndentation:
  EnforcedStyle: indented

SignalException:
  EnforcedStyle: only_raise
