# encoding: UTF-8

module Pronto
  module Formatter
    class GithubFormatter
      # Used by the GithubFormatter and GithubPullRequestFormatter classes
      #
      # Provides convenience methods to format the info from a Pronto runner
      # message into a GitHub comment for posting either on a commit diff or on
      # a PR diff.
      module CommentBuilder
        def comment_from_message(message)
          # e.g.
          # Generated by Pronto::Rubocop. Severity: ⚠️ warning. Lorem ipsum dolor sit
          "Generated by #{message.runner || Pronto}. Severity: #{format_level(message.level)}. #{message.msg}"
        end

        def format_level(level)
          prefix = case level
          when :fatal
            "❌"
          when :error
            "❗"
          when :warning
            "⚠️"
          end

          [prefix, level].join(' ')
        end
      end
    end
  end
end
